// resources/js/products.js
import { getAllItems, addItem, updateItem, deleteItem } from './db.js';
import { getSetting, updateSetting } from './settings-manager.js';
import { renderPagination } from './partials/pagination.js';
// === СПИСОК КАТЕГОРИЙ (можно расширять) ===
const PREDEFINED_CATEGORIES = [
    'Телефон',
    'Планшет',
    'Ноутбук',
    'Наушники',
    'Часы',
    'Аксессуары',
    'Компьютер',
    'Монитор'
];

let autoGeneratedSku = null; // Храним сгенерированный SKU для текущего товара

let currentPage = 1;
let currentPageSize = 10;
let currentFilters = {};
let selectedRows = new Map();
let ctxTargetId = null;

// === ИНИЦИАЛИЗАЦИЯ ===
// === ИНИЦИАЛИЗАЦИЯ ===
document.addEventListener('DOMContentLoaded', async () => {
    console.log('📄 DOMContentLoaded fired');
    
    if (typeof Neutralino !== 'undefined') {
        console.log('🔌 Neutralino available');
        Neutralino.init();
    }
    
    console.log('⏳ Waiting for database...');
    await waitForDatabase();
    console.log('✅ Database ready, loading products...');
    
    // Загружаем порог из настроек
    await loadLowStockThreshold();
    
    await loadProducts();
    console.log('✅ Products loaded, setting up listeners...');
    
    setupEventListeners();
    populateCategoryDropdowns();
    
    console.log('✅ Products page initialized');
});

async function waitForDatabase() {
    if (window.isDatabaseReady) return;
    return new Promise(resolve => {
        const check = () => window.isDatabaseReady ? resolve() : setTimeout(check, 50);
        check();
    });
}

// Функция загрузки порога
async function loadLowStockThreshold() {
    const thresholdInput = document.getElementById('lowStockThreshold');
    if (thresholdInput) {
        const savedThreshold = await getSetting('inventory.lowStockThreshold', 10);
        thresholdInput.value = savedThreshold;
    }
}

// Заполнение выпадающих списков категорий
function populateCategoryDropdowns() {
    // Фильтр на странице
    const filterSelect = document.getElementById('filterCategory');
    if (filterSelect) {
        filterSelect.innerHTML = '<option value="">Все категории</option>' +
            PREDEFINED_CATEGORIES.map(cat => `<option value="${cat}">${cat}</option>`).join('');
    }
    
    // Форма создания
    const createCategory = document.getElementById('productCategory');
    if (createCategory) {
        createCategory.setAttribute('list', 'categoryListCreate');
    }
    
    // Форма редактирования
    const editCategory = document.getElementById('editProductCategory');
    if (editCategory) {
        editCategory.setAttribute('list', 'categoryListEdit');
    }
    
    // Добавляем datalist для автодополнения (если нет)
    if (!document.getElementById('categoryListCreate')) {
        const datalistCreate = document.createElement('datalist');
        datalistCreate.id = 'categoryListCreate';
        PREDEFINED_CATEGORIES.forEach(cat => {
            const option = document.createElement('option');
            option.value = cat;
            datalistCreate.appendChild(option);
        });
        document.body.appendChild(datalistCreate);
        
        const datalistEdit = document.createElement('datalist');
        datalistEdit.id = 'categoryListEdit';
        PREDEFINED_CATEGORIES.forEach(cat => {
            const option = document.createElement('option');
            option.value = cat;
            datalistEdit.appendChild(option);
        });
        document.body.appendChild(datalistEdit);
    }
}

// Автогенерация SKU
function generateSku(category) {
    if (!category) return '';
    
    // Первые 2 буквы (или символа) категории
    const prefix = category.substring(0, 2).toUpperCase();
    return prefix;
}

// Получение следующего ID для SKU
async function getNextSkuId() {
    try {
        const products = await getAllItems('products');
        const maxId = products.reduce((max, p) => Math.max(max, p.id || 0), 0);
        return maxId + 1;
    } catch (error) {
        console.error('Error getting next SKU ID:', error);
        return 1;
    }
}

// === ЗАГРУЗКА ДАННЫХ ===
async function loadProducts() {
    console.log('🚀 loadProducts started');
    
    const tbody = document.querySelector('#productTable tbody');
    if (tbody) {
        console.log('✅ Found tbody');
        tbody.innerHTML = '<tr><td colspan="7" style="text-align: center; padding: 20px;">⏳ Загрузка...</td></tr>';
    } else {
        console.error('❌ tbody not found!');
        return;
    }
    
    try {
        console.log('📦 Loading products from database...');
        let products = await getAllItems('products');
        
        console.log(`📊 Raw products from DB:`, products);
        console.log(`📊 Total products: ${products.length}`);
        
        // Применяем фильтры
        if (currentFilters.category) {
            products = products.filter(p => p.category === currentFilters.category);
        }
        if (currentFilters.name) {
            const search = currentFilters.name.toLowerCase();
            products = products.filter(p => 
                (p.name && p.name.toLowerCase().includes(search)) || 
                (p.sku && p.sku.toLowerCase().includes(search))
            );
        }
        if (currentFilters.status) {
            products = products.filter(p => p.is_active === (currentFilters.status === 'active'));
        }
        
        console.log(`📊 Products after filters: ${products.length}`);
        
        // Сортировка
        products.sort((a, b) => (b.id || 0) - (a.id || 0));
        
        // Пагинация
        const total = products.length;
        const start = (currentPage - 1) * currentPageSize;
        const pagedProducts = products.slice(start, start + currentPageSize);
        
        console.log(`📊 Paged products: ${pagedProducts.length}, page: ${currentPage}`);
        console.log('🎨 Calling renderTable...');
        
        renderTable(pagedProducts);
        
        console.log('📄 Calculating pagination...');
        const totalPages = Math.ceil(total / currentPageSize);
        
        const paginationEl = document.getElementById('pagination');
        const paginationInfoEl = document.getElementById('paginationInfo');
        
        console.log('📍 Pagination elements:', paginationEl, paginationInfoEl);
        
        if (paginationEl && paginationInfoEl) {
            renderPagination(
                paginationEl,
                paginationInfoEl,
                currentPage,
                totalPages,
                total,
                currentPageSize,
                goToPage
            );
            console.log('✅ Pagination rendered');
        } else {
            console.warn('⚠️ Pagination elements not found');
        }
        
        console.log('✅ loadProducts completed successfully');
        
    } catch (error) {
        console.error('❌ Error in loadProducts:', error);
        console.error('Stack:', error.stack);
        
        if (tbody) {
            tbody.innerHTML = `<tr><td colspan="7" style="text-align: center; color: #ef4444;">❌ Ошибка: ${error.message}</td></tr>`;
        }
    }
}

function renderTable(products) {
    console.log('🎨 renderTable called with:', products);
    
    const shouldAnimate = getSetting('ui.animateRows');
    const tbody = document.querySelector('#productTable tbody');
    
    // Получаем текущий порог
    const lowStockThreshold = parseInt(document.getElementById('lowStockThreshold')?.value) || 10;
    
    if (!tbody) {
        console.error('❌ Table body not found!');
        return;
    }
    
    if (!products || products.length === 0) {
        console.log('⚠️ No products to render');
        tbody.innerHTML = '<tr><td colspan="7" style="text-align: center; padding: 40px; color: #94a3b8;"> Нет товаров. Добавьте первый товар!</td></tr>';
        return;
    }
    
    try {
        tbody.innerHTML = products.map((product, index) => {
            console.log('📦 Rendering product:', product);
            
            const animClass = shouldAnimate ? 'table-row-animate' : '';
            const animDelay = shouldAnimate ? `style="animation-delay: ${index * 0.04}s;"` : '';
            
            const statusClass = product.is_active ? 'badge-active' : 'badge-inactive';
            const statusText = product.is_active ? 'В продаже' : 'Снят';
            
            // Проверка на null/undefined значения
            const sku = product.sku || 'N/A';
            const category = product.category || 'Без категории';
            const name = product.name || 'Без названия';
            const price = parseFloat(product.price) || 0;
            const quantity = parseInt(product.quantity) || 0;
            
            // Проверка на низкий остаток
            const isLowStock = quantity < lowStockThreshold;
            const stockCellStyle = isLowStock 
                ? 'text-align: center; background: #fef3c7; color: #d97706; font-weight: 600; border-radius: 4px; padding: 2px 8px;' 
                : 'text-align: center;';
            
            return `
            <tr data-id="${product.id}" 
                class="${animClass}" 
                ${animDelay}
                onclick="handleRowClick(event, ${product.id})">
                <td><strong>${sku}</strong></td>
                <td>${category}</td>
                <td>${name}</td>
                <td style="text-align: right;">${price.toFixed(2)} ₽</td>
                <td style="${stockCellStyle}">${quantity}</td>
                <td><span class="badge ${statusClass}">${statusText}</span></td>
            </tr>`; 
        }).join('');
        
        console.log('✅ Table rendered successfully');
        
    } catch (error) {
        console.error('❌ Error rendering table:', error);
        tbody.innerHTML = `<tr><td colspan="7" style="text-align: center; color: #ef4444;">❌ Ошибка рендеринга</td></tr>`;
    }
}

window.goToPage = function(newPage) {
    currentPage = newPage;
    loadProducts();
};

// === ВЫДЕЛЕНИЕ СТРОК ===
window.handleRowClick = function(event, id) {
    event.preventDefault();
    const row = event.currentTarget;
    const modifier = getSetting('ui.selectionModifier') || 'shift';
    const isModifier = modifier === 'shift' ? event.shiftKey : (event.ctrlKey || event.metaKey);

    if (isModifier) {
        if (selectedRows.has(id)) selectedRows.delete(id);
        else selectedRows.set(id, row);
    } else {
        selectedRows.clear();
        selectedRows.set(id, row);
    }
    updateSelectionUI();
};

window.updateSelectionUI = function() {
    document.querySelectorAll('.crm-table tbody tr').forEach(tr => tr.classList.remove('selected'));
    selectedRows.forEach(row => row.classList.add('selected'));

    const bar = document.getElementById('bulkActionBar');
    const countBadge = document.getElementById('selectedCount');
    const btnEdit = document.getElementById('btnBulkEdit');
    const btnDelete = document.getElementById('btnBulkDelete');
    const count = selectedRows.size;

    if (count > 0) {
        bar.classList.add('visible');
        countBadge.textContent = count;
        btnEdit.disabled = count !== 1;
        btnDelete.disabled = false;
    } else {
        bar.classList.remove('visible');
    }
};

window.clearSelection = function() {
    selectedRows.clear();
    updateSelectionUI();
};

// === КОНТЕКСТНОЕ МЕНЮ ===
document.addEventListener('contextmenu', (e) => {
    const row = e.target.closest('tr');
    if (!row || !row.dataset.id) return;
    e.preventDefault();
    
    ctxTargetId = parseInt(row.dataset.id);
    showContextMenu(e.pageX, e.pageY);
});

function showContextMenu(x, y) {
    const menu = document.getElementById('ctxMenu');
    const btnEdit = document.getElementById('ctxEdit');
    const btnDelete = document.getElementById('ctxDelete');
    
    btnEdit.disabled = false;
    btnDelete.disabled = false;

    const finalX = Math.min(x, window.innerWidth - 190);
    const finalY = Math.min(y, window.innerHeight - 130);
    
    menu.style.left = `${finalX}px`;
    menu.style.top = `${finalY}px`;
    menu.style.display = 'block';
}

document.addEventListener('click', (e) => {
    if (!e.target.closest('.ctx-menu')) {
        document.getElementById('ctxMenu').style.display = 'none';
    }
});

window.ctxEditAction = async function() {
    document.getElementById('ctxMenu').style.display = 'none';
    if (ctxTargetId) {
        await openEditProduct(ctxTargetId);
    }
};

window.ctxDeleteAction = async function() {
    document.getElementById('ctxMenu').style.display = 'none';
    if (ctxTargetId) {
        await deleteProduct(ctxTargetId);
    }
};

// === РЕДАКТИРОВАНИЕ И УДАЛЕНИЕ ===
window.openEditProduct = async function(id) {
    try {
        const products = await getAllItems('products');
        const product = products.find(p => p.id === id);
        if (!product) { showToast('❌ Товар не найден'); return; }
        
        document.getElementById('editProductId').value = product.id;
        document.getElementById('editProductSku').value = product.sku; 
        document.getElementById('editProductSku').removeAttribute('readonly'); 
        document.getElementById('editProductCategory').value = product.category;
        document.getElementById('editProductName').value = product.name;
        document.getElementById('editProductDescription').value = product.description || '';
        document.getElementById('editProductPrice').value = product.price;
        document.getElementById('editProductQuantity').value = product.quantity;
        document.getElementById('editProductStatus').value = product.is_active ? 'active' : 'inactive';
        
        openModal('editProductModal');
    } catch (err) {
        showToast('❌ Ошибка: ' + err.message);
    }
};

window.deleteProduct = async function(id) {
    if (!confirm('Удалить этот товар?')) return;
    
    try {
        await deleteItem('products', id);
        if (window.saveDataToFile) await window.saveDataToFile();
        showToast('✅ Товар удален');
        loadProducts();
    } catch (err) {
        showToast('❌ Ошибка: ' + err.message);
    }
};

window.editSelected = async function() {
    if (selectedRows.size !== 1) return;
    const [id] = selectedRows.keys();
    await openEditProduct(id);
};

window.deleteSelected = async function() {
    const count = selectedRows.size;
    if (count === 0) return;
    if (!confirm(`Удалить ${count} товаров?`)) return;

    try {
        for (const id of Array.from(selectedRows.keys())) {
            await deleteItem('products', id);
        }
        if (window.saveDataToFile) await window.saveDataToFile();
        window.clearSelection();
        showToast(`✅ Удалено товаров: ${count}`);
        loadProducts();
    } catch (err) {
        showToast('❌ Ошибка: ' + err.message);
    }
};

// === ОБРАБОТЧИКИ СОБЫТИЙ ===
function setupEventListeners() {
    // Форма создания
    document.getElementById('createProductForm').addEventListener('submit', async (e) => {
        e.preventDefault();
        await handleCreateProduct();
    });

    // Обработчик изменения порога низкого остатка
    const thresholdInput = document.getElementById('lowStockThreshold');
    if (thresholdInput) {
        thresholdInput.addEventListener('change', async (e) => {
            const newValue = parseInt(e.target.value);
            if (!isNaN(newValue) && newValue >= 0) {
                // Сохраняем в настройки
                const { updateSetting } = await import('./settings-manager.js');
                await updateSetting('inventory.lowStockThreshold', newValue);
                
                // Перерисовываем таблицу с новым порогом
                loadProducts();
                
                // Показываем уведомление
                showToast(`✅ Порог низкого остатка установлен: ${newValue}`);
            }
        });
        
        // Также обновляем при вводе (без сохранения, только предпросмотр)
        thresholdInput.addEventListener('input', () => {
            loadProducts();
        });
    }

    // Автогенерация SKU при изменении категории (в режиме создания)
    const createCategory = document.getElementById('productCategory');
    if (createCategory) {
        createCategory.addEventListener('input', async (e) => {
            const category = e.target.value;
            if (category) {
                const prefix = generateSku(category);
                const nextId = await getNextSkuId();
                const generatedSku = `${prefix}-${nextId}`;
                
                // Показываем превью (опционально)
                console.log(`📦 Будет сгенерирован SKU: ${generatedSku}`);
            }
        });
    }    
    // Форма редактирования
    document.getElementById('editProductForm').addEventListener('submit', async (e) => {
        e.preventDefault();
        await handleEditProduct();
    });
    
    // Фильтры
    document.getElementById('btnApplyFilters').addEventListener('click', () => {
        currentFilters = {
            category: document.getElementById('filterCategory').value || null,
            name: document.getElementById('filterName').value || null,
            status: document.getElementById('filterStatus').value || null
        };
        currentPage = 1;
        loadProducts();
    });
    
    document.getElementById('btnResetFilters').addEventListener('click', () => {
        document.getElementById('filterCategory').value = '';
        document.getElementById('filterName').value = '';
        document.getElementById('filterStatus').value = '';
        currentFilters = {};
        currentPage = 1;
        loadProducts();
        populateCategoryFilter();
    });
    
    // Пагинация
    document.getElementById('pageSize').addEventListener('change', (e) => {
        currentPageSize = parseInt(e.target.value);
        currentPage = 1;
        loadProducts();
    });
}

async function handleCreateProduct() {
    const category = document.getElementById('productCategory').value;
    
    // Генерируем SKU автоматически
    const skuPrefix = generateSku(category);
    const nextId = await getNextSkuId();
    const finalSku = `${skuPrefix}-${nextId}`;
    
    const formData = {
        sku: finalSku, 
        category: category,
        name: document.getElementById('productName').value,
        description: document.getElementById('productDescription').value,
        price: parseFloat(document.getElementById('productPrice').value),
        quantity: parseInt(document.getElementById('productQuantity').value),
        is_active: document.getElementById('productStatus').value === 'active',
        created_at: new Date().toISOString()
    };
    
    try {
        await addItem('products', formData);
        if (window.saveDataToFile) await window.saveDataToFile();
        
        showToast(`✅ Товар добавлен (SKU: ${finalSku})`);
        document.getElementById('createProductForm').reset();
        closeModal('createProductModal');
        loadProducts();
        populateCategoryDropdowns(); // Обновляем список категорий
    } catch (error) {
        showToast('❌ Ошибка: ' + error.message);
    }
}

async function handleEditProduct() {
    const id = parseInt(document.getElementById('editProductId').value);
    const updates = {
        sku: document.getElementById('editProductSku').value.toUpperCase(), //  Можно изменить
        category: document.getElementById('editProductCategory').value,
        name: document.getElementById('editProductName').value,
        description: document.getElementById('editProductDescription').value,
        price: parseFloat(document.getElementById('editProductPrice').value),
        quantity: parseInt(document.getElementById('editProductQuantity').value),
        is_active: document.getElementById('editProductStatus').value === 'active',
        updated_at: new Date().toISOString()
    };
    
    try {
        await updateItem('products', id, updates);
        if (window.saveDataToFile) await window.saveDataToFile();
        
        showToast('✅ Товар обновлен');
        closeModal('editProductModal');
        loadProducts();
        populateCategoryDropdowns();
    } catch (error) {
        showToast('❌ Ошибка: ' + error.message);
    }
}

// === ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ ===
function showToast(message) {
    const toast = document.createElement('div');
    toast.className = 'toast';
    toast.textContent = message;
    toast.style.cssText = 'position: fixed; bottom: 20px; right: 20px; background: #333; color: white; padding: 12px 20px; border-radius: 8px; z-index: 9999; animation: fadeIn 0.3s;';
    document.body.appendChild(toast);
    setTimeout(() => toast.remove(), 3000);
}

window.openModal = function(modalId) {
    document.getElementById(modalId).classList.add('active');
    document.body.style.overflow = 'hidden';
};

window.closeModal = function(modalId) {
    document.getElementById(modalId).classList.remove('active');
    document.body.style.overflow = '';
};

window.closeModalOnOverlay = function(event, modalId) {
    if (event.target.id === modalId) {
        window.closeModal(modalId);
    }
};

// Глобальный экспорт
window.openEditProduct = window.openEditProduct;
window.deleteProduct = window.deleteProduct;
window.editSelected = window.editSelected;
window.deleteSelected = window.deleteSelected;
window.clearSelection = window.clearSelection;
window.ctxEditAction = window.ctxEditAction;
window.ctxDeleteAction = window.ctxDeleteAction;